name: Deployment

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: pull images
        run: |
          docker pull thehetsolanki/paaniwale-frontend:preview
          docker pull thehetsolanki/paaniwale-backend:preview

      - name: updating the tag from preview to latest
        run: |
          docker tag thehetsolanki/paaniwale-frontend:preview thehetsolanki/paaniwale-frontend:latest
          docker tag thehetsolanki/paaniwale-backend:preview thehetsolanki/paaniwale-backend:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HOST }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push ${{secrets.DOCKER_HOST}}/paaniwale-frontend:latest
          docker push ${{secrets.DOCKER_HOST}}/paaniwale-backend:latest

      - name: Deploy to droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /home/deploy
            docker compose pull paaniwale-frontend
            docker compose pull paaniwale-backend
            docker compose up -d paaniwale-frontend
            docker compose up -d paaniwale-backend
            docker compose ps
