name: pr-preview

on:
  pull_request:
    branches: [main]

jobs:
  pr-preview:
    name: pr-preview
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build the application
        run: npm run build
        env:
          VITE_API_BASE_URL_PREVIEW: ${{ secrets.VITE_API_BASE_URL_PREVIEW }}
          VITE_CLOUD_NAME: ${{ secrets.VITE_CLOUD_NAME }}
          VITE_CLOUD_VERSION: ${{ secrets.VITE_CLOUD_VERSION }}
          VITE_CLOUD_API_KEY: ${{ secrets.VITE_CLOUD_API_KEY }}
          VITE_CLOUD_API_SECRET: ${{ secrets.VITE_CLOUD_API_SECRET }}
          VITE_CLOUD_UPLOAD_PRESET: ${{ secrets.VITE_CLOUD_UPLOAD_PRESET }}
          VITE_WHATSAPP_BUSSINESS_ID: ${{ secrets.VITE_WHATSAPP_BUSSINESS_ID }}
          VITE_WHATSAPP_PHONE_NUMBER_ID: ${{ secrets.VITE_WHATSAPP_PHONE_NUMBER_ID }}
          VITE_WHATSAPP_USER_ACCESS_TOKEN: ${{ secrets.VITE_WHATSAPP_USER_ACCESS_TOKEN }}
          VITE_WHATSAPP_API_VERSION: ${{ secrets.VITE_WHATSAPP_API_VERSION }}

      - name: Build Docker image (Frontend)
        run: docker build -t ${{ secrets.DOCKER_HOST }}/paaniwale-frontend:preview .

      - name: Build Docker image (Backend)
        run: |
          cd server/API
          docker build -t ${{ secrets.DOCKER_HOST }}/paaniwale-backend:preview .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HOST }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push ${{secrets.DOCKER_HOST}}/paaniwale-frontend:preview
          docker push ${{secrets.DOCKER_HOST}}/paaniwale-backend:preview

      - name: Deploy to droplet (preview)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /home/preview
            docker compose pull paaniwale-frontend
            docker compose pull paaniwale-backend
            docker compose up -d paaniwale-frontend
            docker compose up -d paaniwale-backend
            docker compose ps
